language: java

addons:
  sonarcloud:
    organization: "lpiskor"
    token:
      secure: ad0aee3456b6832a46d8456096d1f76f8191397c # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=LPiskor_BirthdayGreetingsKata